services:
  - type: web
    name: dynews
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8

      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        sync: false

      - key: ADMIN_USERNAME
        sync: false

      - key: ADMIN_PASSWORD
        sync: false
